### ISSUE TITLE
Change the scope of not OT related maven dependencies to provided 

### ISSUE THREAD

**Issue by gpolaert** [opentracing-contrib/java-agent#35]
Hello,

Some of the Java contribs include the client or the driver dependency in the project (such as the AWS Client contrib or the Mongo contrib). 

Many developers like lean dependencies for the projects and libraries they used, especially to avoid deps conflicts.   

Even if, each README offers a way to exclude some part, I think it would be preferable to set these deps to a scope "provided" and unbind the contrib and the "framework".

The developer will be responsible for adding his own version/client dependencies.

Example:

aws contrib pom.xml
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <scope>provided</scope>
        </dependency>
```
instead of
```
       <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.115</version>
        </dependency>
```

**Comment by objectiser** [comment]
I am away this week but feel free to submit a pr and I will review next week. Thanks.

**Comment by gpolaert** [comment]
Sure, but just let me know if it makes sense :D

**Comment by objectiser** [comment]
Yes it does make sense.

**Comment by objectiser** [comment]
Closing. Please re-open if there are further questions.
