### ISSUE TITLE
Bintray upload problem

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/java-agent#8]
https://travis-ci.org/opentracing-contrib/java-agent/builds/209828604

Thought I had sorted out the bintray issues when I did a test release before - I have used the command in https://github.com/opentracing/opentracing-java/blob/master/RELEASE.md#troubleshooting-invalid-credentials and it works fine locally.

**Comment by objectiser** [comment]
@bhs Any ideas what might be wrong? I haven't used bintray before.

**Comment by bhs** [comment]
@objectiser I am perpetually confused about Bintray. Super hard to debug, too :-/

Sorry that's useless.

**Comment by objectiser** [comment]
@bhs no problem

**Comment by objectiser** [comment]
@bhs Got a bit further - now seems to be failing on sync with maven central. Not sure if I need to be added to a group:  https://issues.sonatype.org/browse/OSSRH-26601 ?

I'm getting:

> Last Sync Errors:
    Could not sync artifact opentracing-agent-parent-0.0.5.pom. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.14.3-02" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'gpbrown' missing 'stage' permission for staging profile: 

Other issue this raises - currently the Java agent is using groupId `io.opentracing.contrib` - should it be using a sub-group?

**Comment by bhs** [comment]
@objectiser that makes sense. Unfortunately I can't help you with that – you'll have to file a ticket with sonatype (which is infuriating!). At least they are quick about it. `manual_processes--`

**Comment by bhs** [comment]
Actually, I guess it'll be better if I create the ticket. Will do so momentarily.

**Comment by bhs** [comment]
@objectiser https://issues.sonatype.org/browse/OSSRH-28784

Please add a comment to the JIRA ticket if I've got the wrong username :)

**Comment by pavolloffay** [comment]
@objectiser I think this can be closed right? Does the release work with `git tag foo; git push origin foo`?

**Comment by objectiser** [comment]
Yes works now
